name: Deploy

on:
  push:
    branches:
      - main
      - develop
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://api-staging.arrivo.nl
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Deploy to Staging
      run: |
        echo "Deploying to staging environment..."
        # Add your staging deployment commands here
        # For example, using SSH to deploy to your staging server:
        # ssh user@staging-server 'docker-compose pull && docker-compose up -d'
        echo "Staging deployment completed"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    environment:
      name: production
      url: https://api.arrivo.nl
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Deploy to Production
      run: |
        echo "Deploying to production environment..."
        # Add your production deployment commands here
        # For example, using SSH to deploy to your production server:
        # ssh user@production-server 'docker-compose pull && docker-compose up -d'
        echo "Production deployment completed"
    
    - name: Notify Deployment
      if: success()
      run: |
        echo "Production deployment successful!"
        # Add notification logic here (Slack, Discord, email, etc.)

  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production]
    if: always() && (needs.deploy-staging.result == 'success' || needs.deploy-production.result == 'success')
    
    steps:
    - name: Health Check Staging
      if: needs.deploy-staging.result == 'success'
      run: |
        echo "Running health check for staging..."
        # curl -f https://api-staging.arrivo.nl/health || exit 1
        echo "Staging health check passed"
    
    - name: Health Check Production
      if: needs.deploy-production.result == 'success'
      run: |
        echo "Running health check for production..."
        # curl -f https://api.arrivo.nl/health || exit 1
        echo "Production health check passed"